[M375] change radios to dropdowns and fix tests
data-mermaid/mermaid-webapp pull request #807
Opened 2023-06-07 22:38 UTC by tienhoah

2023-06-07 22:39 UTC, tienhoah commented
![](https://github.trello.services/images/mini-trello-icon.png) [change radio buttons to dropdowns (Awan)](https://trello.com/c/Zl8VcLR0/375-change-radio-buttons-to-dropdowns-awan)

2023-06-14 14:36 UTC, julia-rom commented on src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitTransectInputs.js
> +  const reefSlopeSelectOptions = getOptions(reefslopes.data)
nitpick on naming - `reefSlopeOptions` (or if you want to keep `Select`, add it to the others too)

2023-06-14 14:37 UTC, julia-rom commented on src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltTransectInputs.js
> +  const reefSlopeSelectOptions = getOptions(reefslopes.data)
same here for `reefSlopeSelectOptions`

2023-06-14 14:40 UTC, julia-rom requested changes
nice job updating all these tests! the drop downs look good.

added a small comment about var names

with regards to the merge conflicts - I renamed the `BenthicAttributeTransectInputs `page to `BenthicPhotoQuadratTransectInputs`

for `FishBeltTransectInputs`, keep both changes to the imports

once that's ready let me know!

2023-06-14 18:24 UTC, julia-rom approved these changes
looks good! tests are also passing, nice work!

2023-06-15 16:19 UTC, merged